Adds mcc configuration.  Adds a .curry file to each benchmark directory (sometimes with minor edits to remove "deriving" clauses).  Not all programs run under mcc.
Cleans up scripts/run-benchmarks to handle failing cases gracefully.

Running on galapagos.
------ Config refcnt-opt ------
reverse              0:05.37
tak                  0:01.98
rfib                 0:03.81
exp3_8               0:00.22
tree_insert          0:01.02
tree_insert_32       0:01.01
primes               0:02.53
queens               0:00.49
wheel_sieve1         0:00.25
wheel_sieve2         0:03.92
------ Config gc-opt ------
reverse              0:02.09
tak                  0:02.01
rfib                 0:03.15
exp3_8               0:00.11
tree_insert          0:01.54
tree_insert_32       0:01.53
primes               0:02.58
queens               0:00.33
wheel_sieve1         0:00.24
wheel_sieve2         0:01.77
------ Config ghc ------
reverse              0:08.86
tak                  0:00.03
rfib                 0:00.11
exp3_8               0:00.12
tree_insert          0:00.57
tree_insert_32       0:00.61
primes               0:00.70
queens               0:00.05
wheel_sieve1         0:00.04
wheel_sieve2         0:00.04
------ Config mcc ------
reverse              0:04.47
tak                  0:00.66
rfib                 0:02.69
exp3_8               0:00.17
tree_insert          (failed)
tree_insert_32       (failed)
primes               0:01.49
queens               0:00.40
wheel_sieve1         0:00.22
wheel_sieve2         (failed)

diff --git a/scripts/make-benchmarks b/scripts/make-benchmarks
--- a/scripts/make-benchmarks
+++ b/scripts/make-benchmarks
@@ -10,8 +10,9 @@ USAGE
     make-benchmarks [-c <config-name>] [-p|q] <benchmark-name> [ ... ]
 
         -c <config-name>
-            The configuration name, which is a file under config or "ghc".
-            This is used to configure the build.  Defaults to "default".
+            The configuration name, which is a file under config or "ghc" or
+            "mcc".  This is used to configure the build.  Defaults to
+            "default".
 
         -p
             Indicates to compile with preprocessed source.  This can be used to
@@ -46,7 +47,7 @@ do
       NCONFIG=1
 
       CONFIG_NAME=$OPTARG
-      if [ "$CONFIG_NAME" == "ghc" ]; then
+      if [ "$CONFIG_NAME" == "ghc" -o "$CONFIG_NAME" == "mcc" ]; then
         IS_SPRITE=0
       fi
       ;;
@@ -76,6 +77,14 @@ if [ $CONFIG_NAME == "ghc" ]; then
       {
         echo >&2 "ghc was not found in PATH, but it is required to use" \
                  "\"ghc\" configuration";
+        exit 1;
+        }
+elif [ $CONFIG_NAME == "mcc" ]; then
+  # Check for mcc.
+  type -P cyc >/dev/null 2>&1 || \
+      {
+        echo >&2 "cyc was not found in PATH, but it is required to use" \
+                 "\"mcc\" configuration";
         exit 1;
         }
 else
@@ -114,6 +123,8 @@ do
   # Generate the main source file.
   if [ $CONFIG_NAME == "ghc" ]; then
     cp $ROOT/benchmarks/$BENCHMARK_NAME/Main.hs $OUTDIR
+  elif [ $CONFIG_NAME == "mcc" ]; then
+    cp $ROOT/benchmarks/$BENCHMARK_NAME/Main.curry $OUTDIR
   else
     cat > $OUTDIR/main.cpp <<EOF
 #include "sprite/sprite.hpp"
@@ -148,6 +159,8 @@ EOF
   
   if [ $CONFIG_NAME == "ghc" ]; then
     ghc -O2 $OUTDIR/Main.hs -o $EXE
+  elif [ $CONFIG_NAME == "mcc" ]; then
+    cyc -m32 $OUTDIR/Main.curry -O2 -o $EXE
   else
     # Use preprocessed source to make debugging and profiling easier.
     function build-pp {
diff --git a/scripts/run-benchmarks b/scripts/run-benchmarks
--- a/scripts/run-benchmarks
+++ b/scripts/run-benchmarks
@@ -39,6 +39,8 @@ if [ "$#" == "0" ]; then
 fi
 
 ROOT=`(cd "\`dirname \"$0\"\`" > /dev/null ; cd ..; pwd)`
+TMP=`mktemp -d`
+trap "rm -rf $TMP" EXIT
 
 for BENCHMARK_NAME in $@
 do
@@ -51,10 +53,18 @@ do
 
   if [[ $SHORT_OUTPUT -ne 0 ]]; then
     printf "%-20s " $BENCHMARK_NAME
-    \time --format="%E" -- $EXE > /dev/null
+    \time --format="%E" -o $TMP/$BENCHMARK_NAME -- $EXE > /dev/null 2>&1
+
+    if [ "$?" -eq 0 ]; then
+      echo `cat $TMP/$BENCHMARK_NAME`
+    else
+      echo "(failed)"
+    fi
+
   else
     echo "------ $BENCHMARK_NAME ------"
     \time $EXE
   fi
+
 done
 
